// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOqFBTYkqZ4WDz7knDAlr-p6iavN1FNE',
    appId: '1:1004826567685:web:9c7462612eb376ec5be86c',
    messagingSenderId: '1004826567685',
    projectId: 'pxp-login-5983f',
    authDomain: 'pxp-login-5983f.firebaseapp.com',
    storageBucket: 'pxp-login-5983f.appspot.com',
    measurementId: 'G-5LS3YGCGVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiUa2EBoZdhLHPaZ5SEZ12o_HbGBLVEbw',
    appId: '1:1004826567685:android:2166ad6e8a40a5315be86c',
    messagingSenderId: '1004826567685',
    projectId: 'pxp-login-5983f',
    storageBucket: 'pxp-login-5983f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsQLnogspAQ5tYZRO7eRSz4GvOM5bCVw',
    appId: '1:1004826567685:ios:bcf41c07ecd107385be86c',
    messagingSenderId: '1004826567685',
    projectId: 'pxp-login-5983f',
    storageBucket: 'pxp-login-5983f.appspot.com',
    iosClientId: '1004826567685-994ov24js8obh3raecddvdoi0q8n5bnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pxpFlutter',
  );
}
